"""add social_url to businesses

Revision ID: 08059bdbcd49
Revises: a8cd4a59fc90
Create Date: 2026-08-20 11:32:25.710458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08059bdbcd49'
down_revision: Union[str, None] = 'a8cd4a59fc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('social_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'social_url')
    # ### end Alembic commands ###
