"""initial schema

Revision ID: 889c661d5991
Revises: 
Create Date: 2026-08-14 23:49:06.798330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889c661d5991'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('website_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_status_history_business_id'), 'lead_status_history', ['business_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_business_id'), 'notes', ['business_id'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('angle', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_business_id'), 'outreach', ['business_id'], unique=False)
    op.create_table('website_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('https_enabled', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('crawl_depth', sa.Integer(), nullable=True),
    sa.Column('has_viewport', sa.Boolean(), nullable=True),
    sa.Column('has_contact_form', sa.Boolean(), nullable=True),
    sa.Column('has_email', sa.Boolean(), nullable=True),
    sa.Column('has_phone', sa.Boolean(), nullable=True),
    sa.Column('has_booking', sa.Boolean(), nullable=True),
    sa.Column('has_faq', sa.Boolean(), nullable=True),
    sa.Column('has_live_chat', sa.Boolean(), nullable=True),
    sa.Column('has_ai_chatbot', sa.Boolean(), nullable=True),
    sa.Column('has_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('has_social_links', sa.Boolean(), nullable=True),
    sa.Column('discovered_email', sa.String(length=255), nullable=True),
    sa.Column('broken_link_count', sa.Integer(), nullable=True),
    sa.Column('mobile_score', sa.Integer(), nullable=True),
    sa.Column('design_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('conversion_score', sa.Integer(), nullable=True),
    sa.Column('customer_experience_score', sa.Integer(), nullable=True),
    sa.Column('website_quality_score', sa.Integer(), nullable=True),
    sa.Column('ai_opportunity_score', sa.Integer(), nullable=True),
    sa.Column('redesign_opportunity_score', sa.Integer(), nullable=True),
    sa.Column('overall_opportunity_score', sa.Integer(), nullable=True),
    sa.Column('quality_category', sa.String(length=50), nullable=True),
    sa.Column('opportunity_types', sa.JSON(), nullable=True),
    sa.Column('audit_summary', sa.Text(), nullable=True),
    sa.Column('opportunity_reasons', sa.JSON(), nullable=True),
    sa.Column('screenshot_desktop_path', sa.String(length=500), nullable=True),
    sa.Column('screenshot_mobile_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_audits_business_id'), 'website_audits', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_audits_business_id'), table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_index(op.f('ix_outreach_business_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_notes_business_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_lead_status_history_business_id'), table_name='lead_status_history')
    op.drop_table('lead_status_history')
    op.drop_table('businesses')
    # ### end Alembic commands ###
