"""add senders table and outreach sender fields

Revision ID: e572b387b323
Revises: 889c661d5991
Create Date: 2026-08-20 10:39:37.589935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e572b387b323'
down_revision: Union[str, None] = '889c661d5991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('outreach', sa.Column('sender_id', sa.String(length=36), nullable=True))
    op.add_column('outreach', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('outreach', sa.Column('sender_title', sa.String(length=255), nullable=True))
    op.add_column('outreach', sa.Column('sender_email', sa.String(length=255), nullable=True))
    op.add_column('outreach', sa.Column('sender_phone', sa.String(length=50), nullable=True))
    op.add_column('outreach', sa.Column('sender_portfolio_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'outreach', 'senders', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outreach', type_='foreignkey')
    op.drop_column('outreach', 'sender_portfolio_url')
    op.drop_column('outreach', 'sender_phone')
    op.drop_column('outreach', 'sender_email')
    op.drop_column('outreach', 'sender_title')
    op.drop_column('outreach', 'sender_name')
    op.drop_column('outreach', 'sender_id')
    op.drop_table('senders')
    # ### end Alembic commands ###
